# Generated by Django 5.0.6 on 2024-05-15 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_reservation'),
        ('reservation', '0007_remove_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservation.reservation'),
        ),
    ]
