# Generated by Django 5.0.6 on 2024-05-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.URLField(blank=True, default='https://th.bing.com/th/id/OIP.Ic4fs6C6iJ5UXHDIlQCkmgHaE8?w=240&h=180&c=7&r=0&o=5&pid=1.7', null=True),
        ),
    ]
