# Generated by Django 5.0.6 on 2024-05-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='number',
        ),
    ]
