# Generated by Django 5.0.6 on 2024-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_room_max_customers_roomtype_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_customers',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
