# Generated by Django 5.0.6 on 2024-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0004_alter_room_max_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
