# Generated by Django 5.0.6 on 2024-05-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0005_roomtype_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='img',
            field=models.URLField(blank=True, default='https://th.bing.com/th/id/R.af2f9ca645743af637cf120723573ffe?rik=5MW4ervdkavFiA&pid=ImgRaw&r=0', null=True),
        ),
    ]
