# Generated by Django 5.0.6 on 2024-05-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_services_img'),
        ('reservation', '0003_reservation_updated_at_alter_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='reservation_services', to='hotel.services'),
        ),
    ]
