# Generated by Django 5.0.6 on 2024-05-15 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_reservation'),
        ('reservation', '0004_reservation_hotel_reservation_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_payment', to='payment.payment'),
        ),
    ]
