# Generated by Django 5.0.6 on 2024-05-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_reservation_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='is_payment',
            new_name='is_paid',
        ),
    ]
