# Generated by Django 5.0.6 on 2024-05-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_rename_is_payment_reservation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='locator',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
